apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 80         # Kamu panggil di http://localhost/api/v1/...
      targetPort: 8080 # Port aplikasi Go kamu